"""Builds k8s/base/postgres-init.yaml from infra/postgres/init/*.sh.

The Compose stack bind-mounts that directory into PostgreSQL. Kubernetes has
no bind mounts, and Kustomize refuses to read files above its own root, so
the scripts have to be carried inside a ConfigMap. Generating it from the
same files keeps one source of truth; the Kubernetes workflow re-runs this
and fails if the result differs, so the copy cannot drift.
"""

import sys
from pathlib import Path

root = Path("/home/benha/projects/knowpilot")
scripts = sorted((root / "infra/postgres/init").glob("*.sh"))
assert scripts, "no init scripts found"

header = """# GENERATED by infra/postgres/init-configmap.py - do not edit.
#
# The same scripts the Compose stack bind-mounts into PostgreSQL
# (infra/postgres/init/). They run once, on an empty data directory: they
# create Keycloak's own database and user inside the same server, revoke the
# CONNECT that PostgreSQL grants to PUBLIC by default, and enable pgvector in
# the application database only.
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
"""

lines = [header]
for script in scripts:
    lines.append("  " + script.name + ": |" + chr(10))
    for line in script.read_text(encoding="utf-8").splitlines():
        lines.append(("    " + line).rstrip() + chr(10))

out = root / "k8s/base/postgres-init.yaml"
generated = "".join(lines)

if "--check" in sys.argv:
    current = out.read_text(encoding="utf-8") if out.exists() else ""
    if current != generated:
        print("k8s/base/postgres-init.yaml is out of date with infra/postgres/init/")
        raise SystemExit(1)
    print("postgres-init.yaml matches the Compose scripts")
else:
    out.write_text(generated, encoding="utf-8", newline=chr(10))
    print("wrote", out, "from", len(scripts), "scripts")
